index:
    path: /
    defaults: { _controller: 'App\Controller\MainController::defaultAction' }
saveitems:
    path: /saveitems/{importid}/{fruit}/{latitude}/{name}/{email}/{color}/{address}
    defaults: { _controller: 'App\Controller\MainController::saveitems' }
getitems:
    path: /getitems
    defaults: { _controller: 'App\Controller\MainController::getitems' }
removeitems:
    path: /removeitems/{id}
    defaults: { _controller: 'App\Controller\MainController::removeitems' }